apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api
spec:
  selector:
    matchLabels:
      app: coordinates-api
  replicas: 3
  template:
    metadata:
      labels:
        app: coordinates-api
    spec:
      containers:
      - name: coordinates-api
        image: dannygoldberg/coordinates_api:v1
        env:
          - name: POSTGRES_HOST
            value: "postgres-0.postgres-svc"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "coordinates_db"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
        ports:
        - containerPort: 8000